### ISSUE TITLE
Extracting PSX binaries from .BIN files?

### ISSUE THREAD

**Issue by oxr463** [RetroReversing/retroReversing#2]
Greetings,

I am interested in learning how more about reverse engineering psx ROMs for the purpose of modding [Front Mission 3](https://en.wikipedia.org/wiki/Front_Mission_3).

PSX ROMs are typically distributed as `.BIN` files (along with `.CUE` files),
however, this file format is not mentioned on the [PS1FileFormats Page](https://github.com/RetroReversing/retroReversing/blob/master/pages/ps1/PS1FileFormats.md).

This is also the case for the `.85` files mentioned on the [PS1_Radare2 Page](https://github.com/RetroReversing/retroReversing/blob/master/pages/ps1/PS1_Radare2.md).

**Comment by RetroGameDeveloper** [comment]
Thank you very much, I have updated the  PS1FileFormats Page to add .BIN and .CUE along with a description for what they are used for and how they compare to the other files listed on that page.

**Comment by oxr463** [comment]
Awesome! Thanks!
