### ISSUE TITLE
PSX game with debug symbol: Syphon Filter (USA) (Demo) contains a .map file

### ISSUE THREAD

**Issue by Wuteva** [RetroReversing/retroReversing#22]
In the link https://www.retroreversing.com/ps1-debug-symbols , section "Demos and Betas with Linker Map file", Syphon Filter (USA) (Demo) is missing. The map file (SIPHON.MAP) can be found on the root directory.

I took a look in ghidra and it seems it doesn't quite match the binary (MainLoop is at 0x800144a4 in ghdira but is at 0x800144C0 in the map file).

I could be wrong about the memory address since I'm quite new to reverse engineering, but I think it can be explained with the date of the .map file versus the binary (.map is dated 1998-12-20 15:01 while SCUS_943.62 is 1998-12-16 03:54).

Still, hopefully someone with more knowledge can use this info to reverse the game I hope! (And if you do, let me know!)

**Comment by RetroGameDeveloper** [comment]
Thank you, this is really interesting information! I hope you don't mind but I have added this information to the page here: https://github.com/RetroReversing/retroReversing/blob/master/pages/ps1/PS1Symbols.md

**Comment by Wuteva** [comment]
No problem!

**Comment by paulsapps** [comment]
Is there a copy of this map file somewhere? 🤔

**Comment by Wuteva** [comment]
Yes, I found it on the demo linked in https://www.youtube.com/watch?v=fcWsRxy0rHw
