### ISSUE TITLE
DS index 404

### ISSUE THREAD

**Issue by drj613** [RetroReversing/retroReversing#226]
Currently the DS index page 404s

https://www.retroreversing.com/ds
![image](https://github.com/user-attachments/assets/c74dc678-a095-4736-b61a-592f99a6f271)

This page was reached via the dropdown.

I assumed that maybe there just wasn't information for the NDS captured on this site, but Google indexed [this page](https://www.retroreversing.com/DSFileFormats) on NDS file formats. The breadcrumb at the top of this page leads right back to that 404 page as well.

**Comment by RetroGameDeveloper** [comment]
Hey thank you for raising this! I added the page now with links to the file formats and a few other DS pages we have. Hopefully we will add more DS content in the near future.

**Comment by drj613** [comment]
Awesome, thank you!! Confirmed fixed 🙇 

This tool may be worth adding to that section. Currently deprecated as the maintainer is working on a better replacement but it's still plenty functional

https://github.com/pleonex/tinke

**Comment by RetroGameDeveloper** [comment]
Thanks that is an excellent recommendation, I have added it to the page and will update when the replacement becomes functional
