### ISSUE TITLE
Add a Section on Sega Saturn Save Games

### ISSUE THREAD

**Issue by slinga-homebrew** [RetroReversing/retroReversing#24]
I would like to request the addition of a section on Sega Saturn save game files/formats. 

Tools to reference:
Copy Saves from Saturn to PC:
- [SS-Save-Parser](https://github.com/hitomi2500/ss-save-parser): QT-based parser for Sega Saturn RAM Backup (aka Power Memory), Internal RAM, and possibly other media images. It can load/save/show image's content and extract/insert/delete single saves in a customizable way. Virtually any sector size (64,256,512,whatever) is suppoted, and conversion is available. Importing of a Datel's compressed images is supported.
- [Save Game Extractor](https://github.com/slinga-homebrew/Save-Game-Extractor): Transmit Sega Saturn save game files as audio to backup on a PC. Based on the amazing minimodem.

Copy Saves from PC to Saturn:
- [Save Game Manager](http://www.rockin-b.de/saturn-savegamemanager.html):  Most useful utility for gamers on SEGA Saturn.  manage files. Supports:

    - copy, delete, format, 
    - compress / decompress file archives (BZip2)
    - update Action Replay firmware (using arflash from ExCyber)
    - split / join files (since v2)
    - dump memory (AR firmware) to file (since v2)
    - export / import files using button commands (since v2)
    - export / import files using human readable base64 text (since v3) (Save Game eXchange over internet)
- [Save Game Copier](https://github.com/slinga-homebrew/Save-Game-Copier): Allows you to burn saves to a CD, boot on a real Saturn, and copy them to the internal memory of the Saturn. Archived project.

**Comment by RetroGameDeveloper** [comment]
This is a great idea, I have added a page here: https://www.retroreversing.com/sega-saturn-save-data/

Is there anything else that would be useful to add to the page?

Also I noticed that you created many of those tools listed, very nice job indeed!

**Comment by slinga-homebrew** [comment]
Thank you the page looks good.
