### ISSUE TITLE
TAD Format - Extra details

### ISSUE THREAD

**Issue by shanepm** [RetroReversing/retroReversing#38]
Using `split_tad_console` (from `twToolsRed`) one can extract the SRL file from a TAD file. I tested with 4 Swords a while back.
Someone on 4chan was distributing [this Python code](https://pastebin.com/7dhXeMWJ), also. Not sure if there's a difference.

One can then use [ninfs](https://github.com/ihaveamac/ninfs) to mount the SRL to a directory and view its contents, e.g. via `mount_srl swords.srl ~/mnt_srl`.
From the sounds of it on a 3DS you can use [GodMode9](https://github.com/d0k3/GodMode9) to convert the SRL to a CIA, or on preview, install the SRL directly.
NO$GBA should be able to launch it too once it's in SRL format.

**Comment by RetroGameDeveloper** [comment]
Thank you very much, this is information I was looking for but couldn't find anywhere, I have added the details to: https://www.retroreversing.com/DSFileFormats Along with a reference back to your information in this ticket.
