### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by mgarcia-org** [RetroReversing/retroReversing#46]
https://www.retroreversing.com/atom.xml doesn't work?

**Comment by RetroGameDeveloper** [comment]
Thanks for letting me know, I have now fixed the RSS feed

**Comment by mgarcia-org** [comment]
Thanks that worked.. but also it should be visible on a page somewhere, rather then having to search the HTML ;)

**Comment by RetroGameDeveloper** [comment]
Excellent point, I have now added a link to the footer that should appear on every page :)

**Comment by mgarcia-org** [comment]
Thank you :)
